### ISSUE TITLE
Navigation item not getting activated

### ISSUE THREAD

**Issue by SutirthaSaha** [dsc712/DCS-WEB#2]
**Describe the bug**
On click of any item in the navigation menu, the item is not getting activated

**To Reproduce**
Click on any navigation item menu

**Expected behavior**
The navigation item clicked should have been activated

**Comment by dsc712** [comment]
I can reproduce the issue. Please someone pick this up.

**Comment by PragnaDas** [comment]
I'm taking this up.

**Comment by dsc712** [comment]
Fix is tested and it is working properly. Thanks.

**Comment by dsc712** [comment]
@SutirthaSaha @PragnaDas Looks like something is wrong with active menu. Home link is not getting active.

**Comment by SutirthaSaha** [comment]
looking into it!

**Comment by dsc712** [comment]
Closing this issue as it is fixed in #7
